services:
  sai-storage:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: sai-storage
    ports:
      - ${SERVER_EXTERNAL_PORT}:${SERVER_PORT}
    env_file:
      - .env
#    depends_on:
#      - mongodb
#      - redis
    networks:
      - sai-network
    restart: unless-stopped
    volumes:
      - ./config.template.yml:/app/config.template.yml

#  mongodb:
#    image: mongo:7.0
#    container_name: mongodb
#    env_file:
#      - .env
#    volumes:
#      - mongodb_data:/data/db
#    networks:
#      - sai-network
#    restart: unless-stopped
#
#  redis:
#    image: redis:7-alpine
#    container_name: redis
#    ports:
#      - "6379:6379"
#    env_file:
#      - .env
#    volumes:
#      - redis_data:/data
#    networks:
#      - sai-network
#    restart: unless-stopped
#
#  mongo-express:
#    image: mongo-express:1.0.0
#    container_name: mongo-express
#    ports:
#      - "8081:8081"
#    env_file:
#      - .env
#    depends_on:
#      - mongodb
#    networks:
#      - sai-network
#    restart: unless-stopped
#
#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    container_name: redis-commander
#    ports:
#      - "8084:8081"
#    env_file:
#      - .env
#    depends_on:
#      - redis
#    networks:
#      - sai-network
#    restart: unless-stopped

#volumes:
#  mongodb_data:
#    driver: local
#  redis_data:
#    driver: local

networks:
  sai-network:
    name: sai-network
    driver: bridge